/**
 * @file accl_packet_processor.h
 * @brief ACCL Packet Processor - Header file
 * 
 * This header defines structures and functions to process ACCL packet traces
 * generated by generate_packet_trace.py. It implements send/recv and collective
 * operations similar to ccl_offload_control.c but based on packet traces.
 */

#ifndef ACCL_PACKET_PROCESSOR_H
#define ACCL_PACKET_PROCESSOR_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

/* Constants matching the Python generator */
#define PROTOCOL_NUMBER 0xACCE
#define PROTOCOL_VERSION 0x01
#define DATAPATH_WIDTH_BYTES 64
#define MAX_PACKETSIZE 4096
#define MAX_EAGER_SIZE 32768

/* Packet Types */
typedef enum {
    PTYPE_DATA_EAGER = 0,
    PTYPE_RNDZV_ADDR = 1,
    PTYPE_RNDZV_DATA = 2,
    PTYPE_RNDZV_COMPLETE = 3,
    PTYPE_COLLECTIVE_DATA = 4
} PacketType;

/* Operation Types */
typedef enum {
    OP_SEND = 0,
    OP_RECV = 1,
    OP_BROADCAST = 2,
    OP_SCATTER = 3,
    OP_GATHER = 4,
    OP_REDUCE = 5,
    OP_ALLGATHER = 6,
    OP_ALLREDUCE = 7,
    OP_REDUCE_SCATTER = 8,
    OP_BARRIER = 9,
    OP_ALLTOALL = 10
} OperationType;

/* Packet Header Structure (64 bytes) */
typedef struct __attribute__((packed)) {
    uint16_t protocol_number;    /* 0xACCE */
    uint16_t version;            /* 0x0001 */
    uint32_t packet_type;        /* PacketType */
    uint32_t operation;          /* OperationType */
    uint32_t src_rank;           /* Source rank */
    uint32_t dst_rank;           /* Destination rank */
    uint32_t tag;                /* Message tag */
    uint32_t session_id;         /* Session ID */
    uint32_t sequence_number;    /* Sequence number */
    uint32_t data_length;        /* Payload length in bytes */
    uint32_t timestamp;          /* Timestamp */
    uint32_t flags;              /* Flags (compression, host memory, etc.) */
    uint64_t address;            /* Address for rendezvous */
    uint32_t payload_segment;    /* Segment number */
    uint32_t total_segments;     /* Total segments */
    uint32_t checksum;           /* Checksum */
} ACCLPacketHeader;

/* Complete Packet Structure */
typedef struct {
    ACCLPacketHeader header;
    uint8_t *payload;            /* Dynamically allocated payload */
} ACCLPacket;

/* Statistics Structure */
typedef struct {
    uint64_t total_packets;
    uint64_t send_recv_packets;
    uint64_t broadcast_packets;
    uint64_t scatter_packets;
    uint64_t gather_packets;
    uint64_t reduce_packets;
    uint64_t allgather_packets;
    uint64_t allreduce_packets;
    uint64_t reduce_scatter_packets;
    uint64_t barrier_packets;
    uint64_t alltoall_packets;
    
    uint64_t eager_packets;
    uint64_t rendezvous_addr_packets;
    uint64_t rendezvous_data_packets;
    uint64_t rendezvous_complete_packets;
    uint64_t collective_packets;
    
    uint64_t total_data_bytes;
    uint64_t bytes_sent;
    uint64_t bytes_received;
} ACCLStatistics;

/* Collective Operation State Tracking */
#define MAX_COLLECTIVE_OPS 128

/* Per-collective-operation state */
typedef struct {
    uint32_t session_id;
    OperationType operation;
    uint32_t root_rank;         /* For rooted collectives */
    uint32_t total_segments;    /* Total segments expected */
    uint32_t segments_received; /* Segments received so far */
    uint64_t total_bytes;       /* Total bytes in operation */
    uint64_t bytes_processed;   /* Bytes processed so far */
    uint32_t ranks_participated;/* Bitmask or counter of ranks */
    bool in_progress;
    bool completed;
} CollectiveOpState;

/* Pending message tracking for send/recv */
#define MAX_PENDING_MSGS 64

typedef struct {
    uint32_t tag;
    uint32_t peer_rank;
    uint32_t session_id;
    uint32_t expected_segments;
    uint32_t received_segments;
    uint64_t bytes;
    bool is_send;               /* true=send, false=recv */
    bool completed;
} PendingMessage;

/* Node State */
typedef struct {
    uint32_t rank;
    uint32_t num_ranks;
    ACCLStatistics stats;
    
    /* State tracking for collective operations */
    CollectiveOpState collective_ops[MAX_COLLECTIVE_OPS];
    uint32_t num_collective_ops;
    
    /* State tracking for point-to-point messages */
    PendingMessage pending_msgs[MAX_PENDING_MSGS];
    uint32_t num_pending_msgs;
    
    /* Barrier synchronization state */
    uint32_t barrier_entered;   /* Count of ranks entered barrier */
    uint32_t barrier_exited;    /* Count of ranks exited barrier */
} ACCLNodeState;

/* Function Prototypes */

/* Initialization and cleanup */
ACCLNodeState* accl_init_node(uint32_t rank, uint32_t num_ranks);
void accl_free_node(ACCLNodeState *node);

/* Packet loading functions */
int accl_load_packets_from_binary(ACCLNodeState *node, const char *filename);
int accl_load_packets_from_hex(ACCLNodeState *node, const char *filename);

/* Packet processing functions */
void accl_process_packet(ACCLNodeState *node, ACCLPacket *packet);

/* Operation-specific handlers */
void accl_handle_send_recv(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_broadcast(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_scatter(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_gather(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_reduce(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_allgather(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_allreduce(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_reduce_scatter(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_barrier(ACCLNodeState *node, ACCLPacket *packet);
void accl_handle_alltoall(ACCLNodeState *node, ACCLPacket *packet);

/* Utility functions */
void accl_print_packet(const ACCLPacket *packet);
void accl_print_statistics(const ACCLStatistics *stats);
const char* accl_packet_type_str(PacketType type);
const char* accl_operation_str(OperationType op);

/* State management helper functions */
CollectiveOpState* accl_find_or_create_collective_op(ACCLNodeState *node, uint32_t session_id, OperationType op);
PendingMessage* accl_find_or_create_pending_msg(ACCLNodeState *node, uint32_t tag, uint32_t peer_rank, bool is_send);

/* Byte order conversion (network to host) */
void accl_ntoh_packet_header(ACCLPacketHeader *header);

#endif /* ACCL_PACKET_PROCESSOR_H */
