/**
 * @file demo_packet_processor.c
 * @brief Demonstration program for ACCL Packet Processor
 * 
 * This program demonstrates how to use the ACCL packet processor to
 * load and process packet traces generated by generate_packet_trace.py.
 * 
 * Usage:
 *   ./demo_packet_processor <node_rank> <binary_file|hex_file>
 * 
 * Examples:
 *   ./demo_packet_processor 3 output_single_node/accl_packet_trace_node3.bin
 *   ./demo_packet_processor 3 output_single_node/accl_packets_raw_hex_node3.txt
 */

#include "accl_packet_processor.h"
#include <stdlib.h>
#include <string.h>

void print_usage(const char *program_name) {
    printf("Usage: %s <node_rank> <packet_file>\n", program_name);
    printf("\n");
    printf("Arguments:\n");
    printf("  node_rank     : Rank of the node to simulate (0-based)\n");
    printf("  packet_file   : Path to binary (.bin) or hex (.txt) packet trace file\n");
    printf("\n");
    printf("Examples:\n");
    printf("  %s 3 output_single_node/accl_packet_trace_node3.bin\n", program_name);
    printf("  %s 3 output_single_node/accl_packets_raw_hex_node3.txt\n", program_name);
    printf("  %s 0 output_all_nodes/accl_packet_trace.bin\n", program_name);
    printf("\n");
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        print_usage(argv[0]);
        return 1;
    }
    
    /* Parse arguments */
    uint32_t node_rank = (uint32_t)atoi(argv[1]);
    const char *filename = argv[2];
    
    printf("========================================\n");
    printf("ACCL Packet Processor Demo\n");
    printf("========================================\n");
    printf("Node Rank: %u\n", node_rank);
    printf("Input File: %s\n", filename);
    printf("========================================\n\n");
    
    /* Initialize node state */
    /* Note: num_ranks will be read from file header */
    ACCLNodeState *node = accl_init_node(node_rank, 8);
    if (!node) {
        fprintf(stderr, "Error: Failed to initialize node\n");
        return 1;
    }
    
    /* Determine file type and load packets */
    int result;
    if (strstr(filename, ".bin") != NULL) {
        printf("Loading binary packet trace...\n");
        result = accl_load_packets_from_binary(node, filename);
    } else if (strstr(filename, ".txt") != NULL) {
        printf("Loading hex packet trace...\n");
        result = accl_load_packets_from_hex(node, filename);
    } else {
        fprintf(stderr, "Error: Unknown file format (use .bin or .txt)\n");
        accl_free_node(node);
        return 1;
    }
    
    if (result != 0) {
        fprintf(stderr, "Error: Failed to load packets\n");
        accl_free_node(node);
        return 1;
    }
    
    printf("\n========================================\n");
    /* Print statistics */
    printf("\n========================================\n");
    printf("Packet Processing Results\n");
    printf("========================================\n");
    accl_print_statistics(&node->stats);
    
    /* Show operation breakdown by protocol */
    printf("\nProtocol Analysis:\n");
    printf("----------------------------------------\n");
    
    if (node->stats.eager_packets > 0 || 
        node->stats.rendezvous_addr_packets > 0 ||
        node->stats.rendezvous_data_packets > 0) {
        printf("Point-to-Point Communication:\n");
        
        if (node->stats.eager_packets > 0) {
            double eager_pct = (node->stats.eager_packets * 100.0) / node->stats.total_packets;
            printf("  Eager Protocol: %lu packets (%.1f%%)\n", 
                   node->stats.eager_packets, eager_pct);
        }
        
        if (node->stats.rendezvous_addr_packets > 0) {
            uint64_t total_rndzv = node->stats.rendezvous_addr_packets +
                                   node->stats.rendezvous_data_packets +
                                   node->stats.rendezvous_complete_packets;
            double rndzv_pct = (total_rndzv * 100.0) / node->stats.total_packets;
            printf("  Rendezvous Protocol: %lu packets (%.1f%%)\n", total_rndzv, rndzv_pct);
            printf("    - Address Exchange: %lu\n", node->stats.rendezvous_addr_packets);
            printf("    - RDMA Data Transfer: %lu\n", node->stats.rendezvous_data_packets);
            printf("    - Completion Notify: %lu\n", node->stats.rendezvous_complete_packets);
        }
    }
    
    if (node->stats.collective_packets > 0) {
        double collective_pct = (node->stats.collective_packets * 100.0) / node->stats.total_packets;
        printf("\nCollective Operations: %lu packets (%.1f%%)\n",
               node->stats.collective_packets, collective_pct);
    }
    
    /* Data volume analysis */
    printf("\nData Volume Analysis:\n");
    printf("----------------------------------------\n");
    printf("Total data transferred: %lu bytes\n", node->stats.total_data_bytes);
    printf("Average packet size: %.2f bytes\n",
           (double)node->stats.total_data_bytes / node->stats.total_packets);
    
    /* Cleanup */
    accl_free_node(node);
    
    printf("\n========================================\n");
    printf("Demo Complete\n");
    printf("========================================\n");
    
    return 0;
}
