/**
 * @file demo_packet_processor.c
 * @brief Demonstration program for ACCL Packet Processor
 * 
 * This program demonstrates how to use the ACCL packet processor to
 * load and process packet traces generated by the PacketTraceGenerator.
 * 
 * PROTOCOL OVERVIEW:
 * ==================
 * 
 * Point-to-Point Communication (SEND/RECV):
 * -----------------------------------------
 * Two protocols are used based on message size (eager_threshold = 32KB):
 * 
 * 1. EAGER PROTOCOL (messages <= 32KB):
 *    - Data sent directly in DATA_EAGER packets
 *    - Messages >4096 bytes are automatically segmented
 *    - Each segment has header fields: payload_segment, total_segments
 *    - Receiver reassembles segments to reconstruct full message
 * 
 * 2. RENDEZVOUS PROTOCOL (messages > 32KB):
 *    Three-phase handshake to optimize large transfers:
 *    - Phase 1: RNDZV_ADDR - Receiver sends buffer address to sender
 *    - Phase 2: RNDZV_DATA - Sender performs RDMA write directly to receiver memory
 *    - Phase 3: RNDZV_COMPLETE - Sender notifies receiver that transfer is complete
 *    This protocol minimizes copies and enables zero-copy RDMA transfers
 * 
 * Collective Operations:
 * ----------------------
 * All collective operations use COLLECTIVE_DATA packet type:
 *    - BROADCAST: Root distributes data to all ranks
 *    - SCATTER: Root sends different chunks to each rank
 *    - GATHER: All ranks send data to root
 *    - REDUCE: Combine data from all ranks with reduction operation
 *    - ALLGATHER: Each rank gathers data from all other ranks
 *    - ALLREDUCE: Reduce + Broadcast (common in ML gradient aggregation)
 *    - REDUCE_SCATTER: Reduce + Scatter combined operation
 *    - BARRIER: Synchronization (small control packets)
 *    - ALLTOALL: Each rank sends unique data to every other rank
 * 
 * All operations respect max_packet_size (4096 bytes) through automatic segmentation.
 * 
 * PACKET STRUCTURE (64-byte header):
 * ===================================
 * Offset | Size | Field           | Description
 * -------|------|-----------------|------------------------------------------
 * 0-1    | 2    | protocol_number | 0xACCE (ACCL protocol identifier)
 * 2-3    | 2    | version         | Protocol version (0x0001)
 * 4-7    | 4    | packet_type     | EAGER, RNDZV_ADDR, RNDZV_DATA, etc.
 * 8-11   | 4    | operation       | SEND, RECV, BROADCAST, SCATTER, etc.
 * 12-15  | 4    | src_rank        | Source node rank
 * 16-19  | 4    | dst_rank        | Destination node rank
 * 20-23  | 4    | tag             | Message matching tag
 * 24-27  | 4    | session_id      | Unique session identifier
 * 28-31  | 4    | sequence_number | Per-connection sequence number
 * 32-35  | 4    | data_length     | Payload size in bytes
 * 36-39  | 4    | timestamp       | Simulation timestamp
 * 40-43  | 4    | flags           | Compression, host_memory flags
 * 44-51  | 8    | address         | 64-bit address for RDMA
 * 52-55  | 4    | payload_segment | Current segment number (0-based)
 * 56-59  | 4    | total_segments  | Total number of segments
 * 60-63  | 4    | checksum        | Simple integrity check
 * 64+    | var  | payload         | Actual data (up to 4096 bytes)
 * 
 * Usage:
 *   ./demo_packet_processor <node_rank> <binary_file|hex_file>
 * 
 * Examples:
 *   ./demo_packet_processor 3 output_single_node/accl_packet_trace_node3.bin
 *   ./demo_packet_processor 3 output_single_node/accl_packets_raw_hex_node3.txt
 * 
 * Baremetal compatible - no external library dependencies.
 */

#include "../src/include/accl_packet_processor.h"
#include <stdlib.h>

/* ============================================================================
 * Baremetal-compatible string functions
 * ============================================================================ */

/**
 * Custom strstr implementation for baremetal systems
 * Returns pointer to first occurrence of needle in haystack, or NULL if not found
 */
static const char* bm_strstr(const char* haystack, const char* needle) {
    if (!haystack || !needle) return NULL;
    if (*needle == '\0') return haystack;
    
    for (; *haystack != '\0'; haystack++) {
        const char* h = haystack;
        const char* n = needle;
        
        while (*h != '\0' && *n != '\0' && *h == *n) {
            h++;
            n++;
        }
        
        if (*n == '\0') {
            return haystack;
        }
    }
    
    return NULL;
}

void print_usage(const char *program_name) {
    printf("Usage: %s <node_rank> <packet_file>\n", program_name);
    printf("\n");
    printf("Arguments:\n");
    printf("  node_rank     : Rank of the node to simulate (0-based)\n");
    printf("  packet_file   : Path to binary (.bin) or hex (.txt) packet trace file\n");
    printf("\n");
    printf("Examples:\n");
    printf("  %s 3 output_single_node/accl_packet_trace_node3.bin\n", program_name);
    printf("  %s 3 output_single_node/accl_packets_raw_hex_node3.txt\n", program_name);
    printf("  %s 0 output_all_nodes/accl_packet_trace.bin\n", program_name);
    printf("\n");
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        print_usage(argv[0]);
        return 1;
    }
    
    /* Parse arguments */
    uint32_t node_rank = (uint32_t)atoi(argv[1]);
    const char *filename = argv[2];
    
    printf("========================================\n");
    printf("ACCL Packet Processor Demo\n");
    printf("========================================\n");
    printf("Node Rank: %u\n", node_rank);
    printf("Input File: %s\n", filename);
    printf("========================================\n\n");
    
    /* Initialize node state */
    /* Note: num_ranks will be read from file header */
    ACCLNodeState *node = accl_init_node(node_rank, 8);
    if (!node) {
        fprintf(stderr, "Error: Failed to initialize node\n");
        return 1;
    }
    
    /* Determine file type and load packets */
    int result;
    if (bm_strstr(filename, ".bin") != NULL) {
        printf("Loading binary packet trace...\n");
        result = accl_load_packets_from_binary(node, filename);
    } else if (bm_strstr(filename, ".txt") != NULL) {
        printf("Loading hex packet trace...\n");
        result = accl_load_packets_from_hex(node, filename);
    } else {
        fprintf(stderr, "Error: Unknown file format (use .bin or .txt)\n");
        accl_free_node(node);
        return 1;
    }
    
    if (result != 0) {
        fprintf(stderr, "Error: Failed to load packets\n");
        accl_free_node(node);
        return 1;
    }
    
    printf("\n========================================\n");
    /* Print statistics */
    printf("\n========================================\n");
    printf("Packet Processing Results\n");
    printf("========================================\n");
    accl_print_statistics(&node->stats);
    
    /* Print SoC memory statistics */
    accl_print_memory_stats(&node->memory);
    
    /* Show operation breakdown by protocol */
    printf("\nProtocol Analysis:\n");
    printf("----------------------------------------\n");
    
    /* Point-to-Point Communication Protocols */
    if (node->stats.eager_packets > 0 || 
        node->stats.rendezvous_addr_packets > 0 ||
        node->stats.rendezvous_data_packets > 0) {
        printf("Point-to-Point Communication (SEND/RECV):\n");
        
        /* Eager Protocol: Used for messages <= 32KB (eager_threshold) */
        if (node->stats.eager_packets > 0) {
            double eager_pct = (node->stats.eager_packets * 100.0) / node->stats.total_packets;
            printf("  Eager Protocol (<=32KB): %llu packets (%.1f%%)\n", 
                   (unsigned long long)node->stats.eager_packets, eager_pct);
            printf("    - Data sent directly in DATA_EAGER packets\n");
            printf("    - Automatic segmentation for messages >4096 bytes\n");
        }
        
        /* Rendezvous Protocol: Used for messages > 32KB */
        if (node->stats.rendezvous_addr_packets > 0) {
            uint64_t total_rndzv = node->stats.rendezvous_addr_packets +
                                   node->stats.rendezvous_data_packets +
                                   node->stats.rendezvous_complete_packets;
            double rndzv_pct = (total_rndzv * 100.0) / node->stats.total_packets;
            printf("  Rendezvous Protocol (>32KB): %llu packets (%.1f%%)\n", 
                   (unsigned long long)total_rndzv, rndzv_pct);
            printf("    - Phase 1 (Address Exchange): %llu RNDZV_ADDR packets\n", 
                   (unsigned long long)node->stats.rendezvous_addr_packets);
            printf("    - Phase 2 (RDMA Data Transfer): %llu RNDZV_DATA packets\n", 
                   (unsigned long long)node->stats.rendezvous_data_packets);
            printf("    - Phase 3 (Completion Notify): %llu RNDZV_COMPLETE packets\n", 
                   (unsigned long long)node->stats.rendezvous_complete_packets);
        }
    }
    
    /* Collective Operations */
    if (node->stats.collective_packets > 0) {
        double collective_pct = (node->stats.collective_packets * 100.0) / node->stats.total_packets;
        printf("\nCollective Operations: %llu packets (%.1f%%)\n",
               (unsigned long long)node->stats.collective_packets, collective_pct);
        printf("  - All collective operations use COLLECTIVE_DATA packet type\n");
        printf("  - Automatic segmentation for data transfers >4096 bytes\n");
        printf("  - Operations: BROADCAST, SCATTER, GATHER, REDUCE, ALLGATHER,\n");
        printf("                ALLREDUCE, REDUCE_SCATTER, BARRIER, ALLTOALL\n");
    }
    
    /* Data volume analysis */
    printf("\nData Volume Analysis:\n");
    printf("----------------------------------------\n");
    printf("Total data transferred: %llu bytes (%.2f KB, %.2f MB)\n", 
           (unsigned long long)node->stats.total_data_bytes,
           node->stats.total_data_bytes / 1024.0,
           node->stats.total_data_bytes / (1024.0 * 1024.0));
    if (node->stats.total_packets > 0) {
        printf("Average packet payload: %.2f bytes\n",
               (double)node->stats.total_data_bytes / node->stats.total_packets);
    }
    printf("Maximum packet size: %d bytes\n", MAX_PACKETSIZE);
    printf("Eager threshold: %d bytes\n", MAX_EAGER_SIZE);
    
    /* Operation breakdown */
    printf("\nOperation Breakdown:\n");
    printf("----------------------------------------\n");
    if (node->stats.send_recv_packets > 0) {
        double pct = (node->stats.send_recv_packets * 100.0) / node->stats.total_packets;
        printf("  SEND/RECV:       %6llu packets (%5.1f%%) - Point-to-point\n",
               (unsigned long long)node->stats.send_recv_packets, pct);
    }
    if (node->stats.broadcast_packets > 0) {
        double pct = (node->stats.broadcast_packets * 100.0) / node->stats.total_packets;
        printf("  BROADCAST:       %6llu packets (%5.1f%%) - Root distributes to all\n",
               (unsigned long long)node->stats.broadcast_packets, pct);
    }
    if (node->stats.scatter_packets > 0) {
        double pct = (node->stats.scatter_packets * 100.0) / node->stats.total_packets;
        printf("  SCATTER:         %6llu packets (%5.1f%%) - Root sends unique data to each rank\n",
               (unsigned long long)node->stats.scatter_packets, pct);
    }
    if (node->stats.gather_packets > 0) {
        double pct = (node->stats.gather_packets * 100.0) / node->stats.total_packets;
        printf("  GATHER:          %6llu packets (%5.1f%%) - All ranks send to root\n",
               (unsigned long long)node->stats.gather_packets, pct);
    }
    if (node->stats.reduce_packets > 0) {
        double pct = (node->stats.reduce_packets * 100.0) / node->stats.total_packets;
        printf("  REDUCE:          %6llu packets (%5.1f%%) - Reduction to root\n",
               (unsigned long long)node->stats.reduce_packets, pct);
    }
    if (node->stats.allgather_packets > 0) {
        double pct = (node->stats.allgather_packets * 100.0) / node->stats.total_packets;
        printf("  ALLGATHER:       %6llu packets (%5.1f%%) - All ranks gather from all\n",
               (unsigned long long)node->stats.allgather_packets, pct);
    }
    if (node->stats.allreduce_packets > 0) {
        double pct = (node->stats.allreduce_packets * 100.0) / node->stats.total_packets;
        printf("  ALLREDUCE:       %6llu packets (%5.1f%%) - Reduce + Broadcast (ML common)\n",
               (unsigned long long)node->stats.allreduce_packets, pct);
    }
    if (node->stats.reduce_scatter_packets > 0) {
        double pct = (node->stats.reduce_scatter_packets * 100.0) / node->stats.total_packets;
        printf("  REDUCE_SCATTER:  %6llu packets (%5.1f%%) - Reduce + Scatter combined\n",
               (unsigned long long)node->stats.reduce_scatter_packets, pct);
    }
    if (node->stats.barrier_packets > 0) {
        double pct = (node->stats.barrier_packets * 100.0) / node->stats.total_packets;
        printf("  BARRIER:         %6llu packets (%5.1f%%) - Synchronization\n",
               (unsigned long long)node->stats.barrier_packets, pct);
    }
    if (node->stats.alltoall_packets > 0) {
        double pct = (node->stats.alltoall_packets * 100.0) / node->stats.total_packets;
        printf("  ALLTOALL:        %6llu packets (%5.1f%%) - Personalized all-to-all\n",
               (unsigned long long)node->stats.alltoall_packets, pct);
    }
    
    /* Cleanup */
    accl_free_node(node);
    
    printf("\n========================================\n");
    printf("Demo Complete\n");
    printf("========================================\n");
    
    return 0;
}
